# Projet: Analyse Matricielle

In [4]:
import numpy as np
import scipy.linalg as lg
from time import time
import matplotlib.pyplot as plt
import scipy.linalg as sc

# Question 3

In [29]:
#1
def MatriceA(n,tau):
    #tau=d/r0
    A=np.eye(n)
    for i in range(n):
        for j in range(n):
            A[i, j] = 1 / (1 + tau**2 * (i - j)**2) # V(d)=1/(1+tau^2) la formule (1)
    return A
n,tau=4,1           
A=MatriceA(n,tau);A


array([[1. , 0.5, 0.2, 0.1],
       [0.5, 1. , 0.5, 0.2],
       [0.2, 0.5, 1. , 0.5],
       [0.1, 0.2, 0.5, 1. ]])

In [71]:
#2
n,tau=4,1           
A=MatriceA(n,tau);A
Pi=np.reshape(np.ones(n),(n,1));Pi


array([[1.],
       [1.],
       [1.],
       [1.]])

In [72]:
def remontee(A,b):
    n,m=np.shape(A)
    n=len(b)
    x=b.copy()
   
    for i in range(n-1,-1,-1):
        for k in range(i+1,n):
            x[i]=x[i]-(np.dot(A[i,k],x[k]))
        x[i]=x[i]/A[i,i]
    return x
remontee(A, Pi)

array([[0.525],
       [0.55 ],
       [0.5  ],
       [1.   ]])

In [10]:
def descente(A,b):
    n,m=np.shape(A)
    n=len(b)
    x=b.copy()
    for i in range(0,n):
        for k in range(0,i):
            x[i]=x[i]-(np.dot(A[i,k],x[k]))
        x[i]=x[i]/A[i,i]
    return x

descente(A,Phi)

array([[1.   ],
       [0.5  ],
       [0.55 ],
       [0.525]])

In [73]:
def solutionLU(A,b):
    I,L,U=lg.lu(A)
    y=remontee(L, b)
    x=descente(U, y)
    return x
solutionLU(A,Pi)

array([[1.        ],
       [1.33333333],
       [1.33928571],
       [1.34099617]])

# Question 4

In [53]:
def toeplitz(t):
    """
    Crée une matrice de Toeplitz symétrique à partir des coefficients de t.
    """
    n=len(t)
    T=np.zeros((n,n))
    #return T
    for i in range(n):
        for j in range(i,n):
            T[i,j]=t[j-i]
            T[j,i]=t[j-i]
           
            
            
    return T
    


In [54]:
# Exemple d'utilisation avec des coefficients t
t=[1,2,3,4,5]
toeplitz(t)

array([[1., 2., 3., 4., 5.],
       [2., 1., 2., 3., 4.],
       [3., 2., 1., 2., 3.],
       [4., 3., 2., 1., 2.],
       [5., 4., 3., 2., 1.]])

In [68]:
def Etape1(t):
    """
    Effectue la première étape de l'algorithme décrit, en utilisant le vecteur t
    pour générer la suite des vecteurs (f1, ..., fn).
    """
    n=len(t)
    f=[]
    # Initialisation de f1
    f1 = np.array([1 / t[0]])
    
    # Calcul de f2 à fn
    for k in range(2, n + 1):
        Tk = np.zeros((k, k))
        # Construction de la matrice Tk-1
        for i in range(k):
            for j in range(k):
                Tk[i, j] = t[i - j]
                # Calcul de Sk-1 f_{k-1}
        Sk_1_fk_1 = np.concatenate(([f1[-1]], f1[:-1]))
         # Calcul de fk
        fk = lg.solve(Tk, Sk_1_fk_1)
        f.append(fk)
                
        return f